
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "control-node"
  config.vm.network "private_network", ip: "192.168.60.100"
  config.vm.synced_folder ".", "/vagrant", type: "nfs"
end
